title: Ray Tracing Problem 
description: [The purpose of this webpage is to introduce the reader to the Ray Tracing Problem.]
theme: jekyll-theme-minimal
plugins:
	- jekyll-toc
	
# TOC Settings
toc:
 min_level: 1
 max_level: 3
 list_class: toc
 list_class: toc__list
 sublist_class: toc__sublist
