remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Ray Tracing Problem 
description: [The purpose of this webpage is to introduce the reader to the Ray Tracing Problem.]
theme: jekyll-theme-minimal
